name: 'CI'
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited
  workflow_call:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
          registry-url: 'https://registry.npmjs.org'
      - name: NPM set register
        run: npm set registry https://registry.npmjs.org
      - name: Install packages
        run: yarn
      - name: Check code lint rules
        run: yarn lint
      - name: Check that the build is correct
        run: yarn build
