name: 'CD release'
on:
  release:
    types: [prereleased, released]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
          registry-url: 'https://registry.npmjs.org'
          submodules: "true"
      - name: NPM set register
        run: npm set registry https://registry.npmjs.org
      - name: NPM whoami
        run: npm whoami
      - name: Install packages
        run: yarn
      - name: Create a build
        run: yarn package
      - name: Publish
        run: node scripts/publish.js
